### ISSUE TITLE
Suppress OctoPrint event scripts during CPQ events

### ISSUE THREAD

**Issue by smartin015** [smartin015/continuousprint#175]
**Is your feature request related to a problem? Please describe.**

OctoPrint's `GCODE Scripts` settings section allows configuring scripts for:

* Before print job starts
* After print job completes
* After print job is cancelled
* After print job is paused
* Before print job is resumed
* Before tool change
* After tool change
* After serial connection to printer is established
* Before serial connection to printer is closed

The "print job" scripts in particular trigger on every file that is run, including those auto-generated by CPQ to e.g. clear the bed. This can cause unexpected behavior when e.g. leveling scripts are put in "After print job completes".

Note that this scripting interface can also be [hooked into](https://docs.octoprint.org/en/master/plugins/hooks.html#octoprint-comm-protocol-scripts), changing behavior by adding to the scripts but not changing the overall number of event options.

**Describe the solution you'd like**

Any script event mentioning `print job` could be suppressed while a CPQ event script is running - and when the event script completes, these scripts would be allowed again. This can be done by patching `octoprint/util/comm.py`'s `sendGcodeScript()` command and swallowing the request whenever a `continuousprint_*.gcode` script is being run from the CPQ folder.

**Describe alternatives you've considered**

Another option would be to totally disable all `print job` events for as long as the queue is actively managed, however the downside would be some redundancy in config.  Users would have to configure a CPQ event script matching the one they have in the old scripts config if they do want that behavior, and they might get confused when making a change in "GCODE Settings" doesn't actually affect the behavior of their prints.

**Additional context**
#70

**Comment by evorotnikov** [comment]
+1 to this issue. I have the same problem now with cleaning script. A bit more context:

- I use  a lot of Before print job starts and After print job completes to prep the printer like preheat, prime hot end etc.
- I specifically don't want it to be part of the GCode of the model because i have several hundred of different type that i need to print and updating all of them every time is a mess
- Since cleaning the bed is also a job in this case all those scripts kick in and start to wait for temperature and prime the nozzle. 

I think there could be also an easy fix for my problem, it will be great not to add clearing bed job into the queue in case cleaning job gcode is empty. This would solve many of my problems. Then i can operate cleaning of the bed from prints using "After print job completes"


@smartin015 could you provide a bit more details about how can i archive it by using `octoprint/util/comm.py` maybe links to any tutorials.

**Comment by smartin015** [comment]
@evorotnikov - thanks for the context! 

My mention of `octoprint/util/comm.py` was more implementation notes for myself than something for others to try - once `2.3.0` is out (hopefully before the new year) I'll submit #180 and publish `2.3.1rc1`. That should hopefully improve behavior for your setup.

**Comment by evorotnikov** [comment]
Thanks @smartin015 looking forward to it, are RCs also published into octoprint plugins repo or is there any instruction on how to install the RC version directly from gihub?

**Comment by smartin015** [comment]
There's a callout [on the docs homepage](https://smartin015.github.io/continuousprint/) for how to switch to using the RC branch :)

**Comment by smartin015** [comment]
This is now live in https://github.com/smartin015/continuousprint/releases/tag/2.4.0
